# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b39a3cb1da68e06e0dbe2d343dc1172a9bc9a13e33517fcfb73f516f139d45a7a072f37ac3e75ce25b7b37dfe8bcec2d190295268ac5274485de64891fe305bf

test:
  secret_key_base: a900722b3afcc864da57779e91997349204a90b83918604e8b1c8316293851b9d488f88b5596fb86715d6eca786e48e182dd5a743ff0dc2310720572fe39e402

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
